name: 'Parse jacoco report'
description: 'Parse jacoco report'
author: prajithp13
branding:
  icon: percent
  color: green
inputs:
  paths:
    description: "Path to jacoco csv report"
    default: "coverage/coverage.csv"
    required: true
  min-coverage:
    description: "The minimum code coverage that is required to pass for overall project"
    default: "90"
    required: false  
  token:
    description: "Github PAT to create PR comments"
    required: true
  badgePath:
    description: "Path where badge will be generated"
    required: false
  report-url:
    description: "URL to the full coverage report"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'

outputs:
  total-coverage:
    description: 'Total code coverage percentage'
  lines-covered:
    description: 'Total lines covered by tests'
  lines-missed:
    description: 'Total lines missed by tests'
  total-lines:
    description: 'Total number of lines'
